In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")
pd.set_option("display.max_columns",None)

# Importing Data

In [2]:
data=pd.read_csv(r"F:\data\PythonProject\Python Project - Bank Lending\XYZCorp_LendingData.txt",\
                 index_col=0, delimiter="\t", low_memory=False)
data.head()

member_id  loan_amnt  funded_amnt  funded_amnt_inv        term  \
id                                                                        
1077501    1296599     5000.0       5000.0           4975.0   36 months   
1077430    1314167     2500.0       2500.0           2500.0   60 months   
1077175    1313524     2400.0       2400.0           2400.0   36 months   
1076863    1277178    10000.0      10000.0          10000.0   36 months   
1075358    1311748     3000.0       3000.0           3000.0   60 months   

         int_rate  installment grade sub_grade                 emp_title  \
id                                                                         
1077501     10.65       162.87     B        B2                       NaN   
1077430     15.27        59.83     C        C4                     Ryder   
1077175     15.96        84.33     C        C5                       NaN   
1076863     13.49       339.31     C        C1       AIR RESOURCES BOARD   
1075358     12.69        67.79     B        B5  University Medical Group   

        emp_length home_ownership  annual_inc verification_status   issue_d  \
id                                                                            
1077501  10+ years           RENT     24000.0            Verified  Dec-2011   
1077430   < 1 year           RENT     30000.0     Source Verified  Dec-2011   
1077175  10+ years           RENT     12252.0        Not Verified  Dec-2011   
1076863  10+ years           RENT     49200.0     Source Verified  Dec-2011   
1075358     1 year           RENT     80000.0     Source Verified  Dec-2011   

        pymnt_plan                                               desc  \
id                                                                      
1077501          n    Borrower added on 12/22/11 > I need to upgra...   
1077430          n    Borrower added on 12/22/11 > I plan to use t...   
1077175          n                                                NaN   
1076863          n    Borrower added on 12/21/11 > to pay for prop...   
1075358          n    Borrower added on 12/21/11 > I plan on combi...   

                purpose                 title zip_code addr_state    dti  \
id                                                                         
1077501     credit_card              Computer    860xx         AZ  27.65   
1077430             car                  bike    309xx         GA   1.00   
1077175  small_business  real estate business    606xx         IL   8.72   
1076863           other              personel    917xx         CA  20.00   
1075358           other              Personal    972xx         OR  17.94   

         delinq_2yrs earliest_cr_line  inq_last_6mths  mths_since_last_delinq  \
id                                                                              
1077501          0.0         Jan-1985             1.0                     NaN   
1077430          0.0         Apr-1999             5.0                     NaN   
1077175          0.0         Nov-2001             2.0                     NaN   
1076863          0.0         Feb-1996             1.0                    35.0   
1075358          0.0         Jan-1996             0.0                    38.0   

         mths_since_last_record  open_acc  pub_rec  revol_bal  revol_util  \
id                                                                          
1077501                     NaN       3.0      0.0    13648.0        83.7   
1077430                     NaN       3.0      0.0     1687.0         9.4   
1077175                     NaN       2.0      0.0     2956.0        98.5   
1076863                     NaN      10.0      0.0     5598.0        21.0   
1075358                     NaN      15.0      0.0    27783.0        53.9   

         total_acc initial_list_status  out_prncp  out_prncp_inv  \
id                                                                 
1077501        9.0                   f        0.0            0.0   
1077430        4.0                   f 

In [7]:
data.shape

(855969, 72)

In [8]:
data1=pd.DataFrame.copy(data)

In [9]:
data1.info

<bound method DataFrame.info of           member_id  loan_amnt  funded_amnt  funded_amnt_inv        term  \
id                                                                         
1077501     1296599     5000.0       5000.0           4975.0   36 months   
1077430     1314167     2500.0       2500.0           2500.0   60 months   
1077175     1313524     2400.0       2400.0           2400.0   36 months   
1076863     1277178    10000.0      10000.0          10000.0   36 months   
1075358     1311748     3000.0       3000.0           3000.0   60 months   
...             ...        ...          ...              ...         ...   
36371250   39102635    10000.0      10000.0          10000.0   36 months   
36441262   39152692    24000.0      24000.0          24000.0   36 months   
36271333   38982739    13000.0      13000.0          13000.0   60 months   
36490806   39222577    12000.0      12000.0          12000.0   60 months   
36271262   38982659    20000.0      20000.0          200

In [78]:
data.describe(include ='all')

loan_amnt    funded_amnt  funded_amnt_inv        term  \
count   855969.000000  855969.000000    855969.000000      855969   
unique            NaN            NaN              NaN           2   
top               NaN            NaN              NaN   36 months   
freq              NaN            NaN              NaN      600221   
first             NaN            NaN              NaN         NaN   
last              NaN            NaN              NaN         NaN   
mean     14745.571335   14732.378305     14700.061226         NaN   
std       8425.340005    8419.471653      8425.805478         NaN   
min        500.000000     500.000000         0.000000         NaN   
25%       8000.000000    8000.000000      8000.000000         NaN   
50%      13000.000000   13000.000000     13000.000000         NaN   
75%      20000.000000   20000.000000     20000.000000         NaN   
max      35000.000000   35000.000000     35000.000000         NaN   

             int_rate    installment   grade sub_grade emp_length  \
count   855969.000000  855969.000000  855969    855969     855969   
unique            NaN            NaN       7        35         11   
top               NaN            NaN       B        B3  10+ years   
freq              NaN            NaN  247998     54958     325151   
first             NaN            NaN     NaN       NaN        NaN   
last              NaN            NaN     NaN       NaN        NaN   
mean        13.192320     436.238072     NaN       NaN        NaN   
std          4.368365     243.726876     NaN       NaN        NaN   
min          5.320000      15.690000     NaN       NaN        NaN   
25%          9.990000     260.550000     NaN       NaN        NaN   
50%         12.990000     382.550000     NaN       NaN        NaN   
75%         15.990000     571.560000     NaN       NaN        NaN   
max         28.990000    1445.460000     NaN       NaN        NaN   

       home_ownership    annual_inc verification_status              issue_d  \
count          855969  8.559690e+05              855969               855969   
unique              6           NaN                   3                  103   
top          MORTGAGE           NaN     Source Verified  2015-10-01 00:00:00   
freq           429106           NaN              318178                48212   
first             NaN           NaN                 NaN  2007-06-01 00:00:00   
last              NaN           NaN                 NaN  2015-12-01 00:00:00   
mean              NaN  7.507119e+04                 NaN                  NaN   
std               NaN  6.426447e+04                 NaN                  NaN   
min               NaN  0.000000e+00                 NaN                  NaN   
25%               NaN  4.500000e+04                 NaN                  NaN   
50%               NaN  6.500000e+04                 NaN                  NaN   
75%               NaN  9.000000e+04                 NaN                  NaN   
max               NaN  9.500000e+06                 NaN                  NaN   

                   purpose            dti earliest_cr_line       open_acc  \
count               855969  855969.000000           855969  855969.000000   
unique                  14            NaN              697            NaN   
top     debt_consolidation            NaN         Aug-2001            NaN   
freq                505392            NaN             6433            NaN   
first                  NaN            NaN              NaN            NaN   
last                   NaN            NaN              NaN            NaN   
mean                   NaN      18.122165              NaN      11.542447   
std                    NaN      17.423629              NaN       5.308094   
min                    NaN       0.000000              NaN       0.000000   
25%                    NaN      11.880000              NaN       8.000000   
50%                    NaN      17.610000              NaN      11.000000   
75%                    NaN      2

In [10]:
for value in ['verification_status_joint']:
    data[value].fillna(data[value].fillna('null'),inplace=True)
pd.set_option('display.max_rows',None)
data.isnull().sum()

member_id                           0
loan_amnt                           0
funded_amnt                         0
funded_amnt_inv                     0
term                                0
int_rate                            0
installment                         0
grade                               0
sub_grade                           0
emp_title                       49443
emp_length                      43061
home_ownership                      0
annual_inc                          0
verification_status                 0
issue_d                             0
pymnt_plan                          0
desc                           734157
purpose                             0
title                              33
zip_code                            0
addr_state                          0
dti                                 0
delinq_2yrs                         0
earliest_cr_line                    0
inq_last_6mths                      0
mths_since_last_delinq         439812
mths_since_l

In [19]:
for value in ['annual_inc_joint','dti_joint']:
    data[value].fillna(data[value].fillna(0),inplace=True)
    pd.set_option('display.max_rows',None)
data.isnull().sum()

member_id                           0
loan_amnt                           0
funded_amnt                         0
funded_amnt_inv                     0
term                                0
int_rate                            0
installment                         0
grade                               0
sub_grade                           0
emp_title                       49443
emp_length                      43061
home_ownership                      0
annual_inc                          0
verification_status                 0
issue_d                             0
pymnt_plan                          0
desc                           734157
purpose                             0
title                              33
zip_code                            0
addr_state                          0
dti                                 0
delinq_2yrs                         0
earliest_cr_line                    0
inq_last_6mths                      0
mths_since_last_delinq         439812
mths_since_l

In [20]:
for col in data.columns: 
    if sum(data[col].isnull())/float(len(data.index)) >=0.5: del data[col]

In [21]:
data.shape

(855969, 54)

In [22]:
data.isnull().sum()

member_id                          0
loan_amnt                          0
funded_amnt                        0
funded_amnt_inv                    0
term                               0
int_rate                           0
installment                        0
grade                              0
sub_grade                          0
emp_title                      49443
emp_length                     43061
home_ownership                     0
annual_inc                         0
verification_status                0
issue_d                            0
pymnt_plan                         0
purpose                            0
title                             33
zip_code                           0
addr_state                         0
dti                                0
delinq_2yrs                        0
earliest_cr_line                   0
inq_last_6mths                     0
open_acc                           0
pub_rec                            0
revol_bal                          0
r

In [23]:
data.columns

Index(['member_id', 'loan_amnt', 'funded_amnt', 'funded_amnt_inv', 'term',
       'int_rate', 'installment', 'grade', 'sub_grade', 'emp_title',
       'emp_length', 'home_ownership', 'annual_inc', 'verification_status',
       'issue_d', 'pymnt_plan', 'purpose', 'title', 'zip_code', 'addr_state',
       'dti', 'delinq_2yrs', 'earliest_cr_line', 'inq_last_6mths', 'open_acc',
       'pub_rec', 'revol_bal', 'revol_util', 'total_acc',
       'initial_list_status', 'out_prncp', 'out_prncp_inv', 'total_pymnt',
       'total_pymnt_inv', 'total_rec_prncp', 'total_rec_int',
       'total_rec_late_fee', 'recoveries', 'collection_recovery_fee',
       'last_pymnt_d', 'last_pymnt_amnt', 'next_pymnt_d', 'last_credit_pull_d',
       'collections_12_mths_ex_med', 'policy_code', 'application_type',
       'annual_inc_joint', 'dti_joint', 'verification_status_joint',
       'acc_now_delinq', 'tot_coll_amt', 'tot_cur_bal', 'total_rev_hi_lim',
       'default_ind'],
      dtype='object')

In [24]:
data=data.drop(['addr_state',
                   'delinq_2yrs',
                  'collection_recovery_fee',
                  'collections_12_mths_ex_med',
                  'last_pymnt_d',
                  'inq_last_6mths',
                  'emp_title',
                  'initial_list_status',
                  'last_pymnt_amnt', 
                  'next_pymnt_d', 
                  'last_credit_pull_d',
                  'member_id', 
                  'tot_coll_amt', 
                  'tot_cur_bal',
                  'policy_code',
                  'pymnt_plan',
                  'revol_bal',
                  'revol_util',
                  'title',
                 'application_type',
                  'zip_code'],axis=1)

In [25]:
data.shape

(855969, 33)

In [26]:
data.isnull().sum()

loan_amnt                        0
funded_amnt                      0
funded_amnt_inv                  0
term                             0
int_rate                         0
installment                      0
grade                            0
sub_grade                        0
emp_length                   43061
home_ownership                   0
annual_inc                       0
verification_status              0
issue_d                          0
purpose                          0
dti                              0
earliest_cr_line                 0
open_acc                         0
pub_rec                          0
total_acc                        0
out_prncp                        0
out_prncp_inv                    0
total_pymnt                      0
total_pymnt_inv                  0
total_rec_prncp                  0
total_rec_int                    0
total_rec_late_fee               0
recoveries                       0
annual_inc_joint                 0
dti_joint           

In [27]:
for x in data.columns[:]:
        if data[x].dtype=='object':
            data[x].fillna(data[x].mode()[0],inplace=True)
        elif data[x].dtype=='int64' or data[x].dtype=='float64':
            data[x].fillna(data[x].mean(),inplace=True)

In [29]:
data.isnull().sum()

loan_amnt                    0
funded_amnt                  0
funded_amnt_inv              0
term                         0
int_rate                     0
installment                  0
grade                        0
sub_grade                    0
emp_length                   0
home_ownership               0
annual_inc                   0
verification_status          0
issue_d                      0
purpose                      0
dti                          0
earliest_cr_line             0
open_acc                     0
pub_rec                      0
total_acc                    0
out_prncp                    0
out_prncp_inv                0
total_pymnt                  0
total_pymnt_inv              0
total_rec_prncp              0
total_rec_int                0
total_rec_late_fee           0
recoveries                   0
annual_inc_joint             0
dti_joint                    0
verification_status_joint    0
acc_now_delinq               0
total_rev_hi_lim             0
default_

In [30]:
data.dtypes

loan_amnt                    float64
funded_amnt                  float64
funded_amnt_inv              float64
term                          object
int_rate                     float64
installment                  float64
grade                         object
sub_grade                     object
emp_length                    object
home_ownership                object
annual_inc                   float64
verification_status           object
issue_d                       object
purpose                       object
dti                          float64
earliest_cr_line              object
open_acc                     float64
pub_rec                      float64
total_acc                    float64
out_prncp                    float64
out_prncp_inv                float64
total_pymnt                  float64
total_pymnt_inv              float64
total_rec_prncp              float64
total_rec_int                float64
total_rec_late_fee           float64
recoveries                   float64
a

In [31]:
corr_data=data.corr(method="pearson")
print(corr_data)

                    loan_amnt  funded_amnt  funded_amnt_inv  int_rate  \
loan_amnt            1.000000     0.999265         0.997601  0.142966   
funded_amnt          0.999265     1.000000         0.998485  0.143116   
funded_amnt_inv      0.997601     0.998485         1.000000  0.143374   
int_rate             0.142966     0.143116         0.143374  1.000000   
installment          0.944870     0.945903         0.944149  0.130468   
annual_inc           0.335209     0.335002         0.334356 -0.073825   
dti                  0.020189     0.020583         0.021489  0.078454   
open_acc             0.198926     0.199432         0.200055 -0.011091   
pub_rec             -0.082199    -0.081858        -0.081008  0.052596   
total_acc            0.222084     0.222039         0.222258 -0.039482   
out_prncp            0.639784     0.641706         0.644011  0.033933   
out_prncp_inv        0.639786     0.641709         0.644023  0.033790   
total_pymnt          0.479612     0.478290         

In [32]:
data.issue_d=pd.to_datetime(data.issue_d)
col_name='issue_d'
print(data[col_name].dtype)

datetime64[ns]


In [33]:
split_date="May-2015"
train=data.loc[data['issue_d']<=split_date]
train=train.drop(['issue_d'],axis=1)
train.shape

(598978, 32)

In [34]:
test=data.loc[data['issue_d']> split_date]
test=test.drop(['issue_d'],axis=1)
test.shape

(256991, 32)

In [35]:
colname=[]
for x in data.columns:
    if data[x].dtype=='object':
        colname.append(x)
colname

['term',
 'grade',
 'sub_grade',
 'emp_length',
 'home_ownership',
 'verification_status',
 'purpose',
 'earliest_cr_line',
 'verification_status_joint']

In [36]:
from sklearn import preprocessing
le=preprocessing.LabelEncoder()
for x in colname:
    train[x]=le.fit_transform(train[x])

In [37]:
from  sklearn import preprocessing
le=preprocessing.LabelEncoder()
for x in colname:
        test[x]=le.fit_transform(test[x])

In [39]:
train.head()

loan_amnt  funded_amnt  funded_amnt_inv  term  int_rate  installment  \
id                                                                              
1077501     5000.0       5000.0           4975.0     0     10.65       162.87   
1077430     2500.0       2500.0           2500.0     1     15.27        59.83   
1077175     2400.0       2400.0           2400.0     0     15.96        84.33   
1076863    10000.0      10000.0          10000.0     0     13.49       339.31   
1075358     3000.0       3000.0           3000.0     1     12.69        67.79   

         grade  sub_grade  emp_length  home_ownership  annual_inc  \
id                                                                  
1077501      1          6           1               5     24000.0   
1077430      2         13          10               5     30000.0   
1077175      2         14           1               5     12252.0   
1076863      2         10           1               5     49200.0   
1075358      1          9           0               5     80000.0   

         verification_status  purpose    dti  earliest_cr_line  open_acc  \
id                                                                         
1077501                    2        1  27.65               257       3.0   
1077430                    1        0   1.00                40       3.0   
1077175                    0       11   8.72               555       2.0   
1076863                    1        9  20.00               203      10.0   
1075358                    1        9  17.94               268      15.0   

         pub_rec  total_acc  out_prncp  out_prncp_inv   total_pymnt  \
id                                                                    
1077501      0.0        9.0        0.0            0.0   5861.071414   
1077430      0.0        4.0        0.0            0.0   1008.710000   
1077175      0.0       10.0        0.0            0.0   3003.653644   
1076863      0.0       37.0        0.0            0.0  12226.302212   
1075358      0.0       38.0      766.9          766.9   3242.170000   

         total_pymnt_inv  total_rec_prncp  total_rec_int  total_rec_late_fee  \
id                                                                             
1077501          5831.78          5000.00         861.07                0.00   
1077430          1008.71           456.46         435.17                0.00   
1077175          3003.65          2400.00         603.65                0.00   
1076863         12226.30         10000.00        2209.33               16.97   
1075358          3242.17          2233.10        1009.07                0.00   

         recoveries  annual_inc_joint  dti_joint  verification_status_joint  \
id                                                                            
1077501        0.00               0.0        0.0                          0   
1077430      117.08               0.0        0.0                          0   
1077175        0.00               0.0        0.0                          0   
1076863        0.00               0.0        0.0                          0   
1075358        0.00               0.0        0.0                          0   

         acc_now_delinq  total_rev_hi_lim  default_ind  
id                                                      
1077501             0.0      32163.574526            0  
1077430             0.0      32163.574526            1  
1077175             0.0      32163.574526            0  
1076863             0.0      32163.574526            0  
1075358             0.0      32163.574526            0

In [40]:
test.head()

loan_amnt  funded_amnt  funded_amnt_inv  term  int_rate  \
id                                                                  
68587652    25000.0      25000.0          25000.0     0      5.32   
66624733    18000.0      18000.0          18000.0     1     19.48   
68446769     7000.0       7000.0           7000.0     0      7.49   
68595206    20000.0      20000.0          20000.0     0     17.97   
68587491    15000.0      15000.0          15000.0     0      6.99   

          installment  grade  sub_grade  emp_length  home_ownership  \
id                                                                    
68587652       752.87      0          0           0               1   
66624733       471.70      4         21           7               3   
68446769       217.72      0          3           1               1   
68595206       722.75      3         18           7               1   
68587491       463.09      0          2           2               1   

          annual_inc  verification_status  purpose    dti  earliest_cr_line  \
id                                                                            
68587652    150000.0                    0        1   9.54               197   
66624733    150000.0                    0        2   9.39               374   
68446769     59000.0                    0        1  13.06               582   
68595206    180000.0                    0        2  25.10                29   
68587491     93000.0                    0        1  14.86               579   

          open_acc  pub_rec  total_acc  out_prncp  out_prncp_inv  total_pymnt  \
id                                                                              
68587652       7.0      0.0       18.0   24357.97       24357.97       682.67   
66624733      18.0      1.0       27.0   17820.50       17820.50       286.64   
68446769      10.0      0.0       34.0    7000.00        7000.00         0.00   
68595206      13.0      0.0       30.0   20000.00       20000.00         0.00   
68587491       8.0      0.0       17.0   15000.00       15000.00         0.00   

          total_pymnt_inv  total_rec_prncp  total_rec_int  total_rec_late_fee  \
id                                                                              
68587652           682.67           642.03          40.64                 0.0   
66624733           286.64           179.50         107.14                 0.0   
68446769             0.00             0.00           0.00                 0.0   
68595206             0.00             0.00           0.00                 0.0   
68587491             0.00             0.00           0.00                 0.0   

          recoveries  annual_inc_joint  dti_joint  verification_status_joint  \
id                                                                             
68587652         0.0               0.0        0.0                          3   
66624733         0.0               0.0        0.0                          3   
68446769         0.0               0.0        0.0                          3   
68595206         0.0               0.0        0.0                          3   
68587491         0.0               0.0        0.0                          3   

          acc_now_delinq  total_rev_hi_lim  default_ind  
id                                                       
68587652             0.0           45500.0            0  
66624733             0.0           34500.0            0  
68446769             0.0           43200.0            0  
68595206             0.0           64200.0            0  
68587491             0.0           34500.0            0

In [42]:
X_train=train.values[:,:-1]
Y_train=train.values[:,-1]

In [43]:
print(Y_train)
X_test=test.values[:,:-1]
Y_test=test.values[:,-1]

print(Y_test)

[0. 1. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]


In [44]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(X_train)
X=scaler.transform(X_train)
print(X_train)

[[ 5000.          5000.          4975.         ...     0.
      0.         32163.57452552]
 [ 2500.          2500.          2500.         ...     0.
      0.         32163.57452552]
 [ 2400.          2400.          2400.         ...     0.
      0.         32163.57452552]
 ...
 [13000.         13000.         13000.         ...     0.
      0.         18000.        ]
 [12000.         12000.         12000.         ...     0.
      0.         27000.        ]
 [20000.         20000.         20000.         ...     0.
      0.         41700.        ]]


In [45]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(X_test)
X=scaler.transform(X_test)
print(X_test)

[[2.5000e+04 2.5000e+04 2.5000e+04 ... 3.0000e+00 0.0000e+00 4.5500e+04]
 [1.8000e+04 1.8000e+04 1.8000e+04 ... 3.0000e+00 0.0000e+00 3.4500e+04]
 [7.0000e+03 7.0000e+03 7.0000e+03 ... 3.0000e+00 0.0000e+00 4.3200e+04]
 ...
 [2.5000e+04 2.5000e+04 2.5000e+04 ... 3.0000e+00 0.0000e+00 4.9600e+04]
 [2.5000e+04 2.5000e+04 2.5000e+04 ... 3.0000e+00 0.0000e+00 4.3800e+04]
 [2.4675e+04 2.4675e+04 2.4675e+04 ... 3.0000e+00 0.0000e+00 1.0300e+05]]


# Decision Tree Model

In [75]:
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier(criterion='entropy',max_leaf_nodes=15,max_depth=20,random_state=10,splitter="best")
model.fit(X_train,Y_train)


DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=20,
                       max_features=None, max_leaf_nodes=15,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=10, splitter='best')

In [76]:
Y_pred=model.predict(X_test)
print(Y_pred)

[0. 0. 0. ... 0. 0. 0.]


In [77]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)
print(classification_report(Y_test,Y_pred))
acc=accuracy_score(Y_test,Y_pred)
print('Accuracy of the model:',acc)

[[256569    111]
 [    63    248]]
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00    256680
         1.0       0.69      0.80      0.74       311

    accuracy                           1.00    256991
   macro avg       0.85      0.90      0.87    256991
weighted avg       1.00      1.00      1.00    256991

Accuracy of the model: 0.9993229334879432


# cross validation

In [63]:
Y_pred=model.predict(X_test)
print(list(zip(Y_test,Y_pred)))  



IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [64]:
Y_pred_prob=model.predict_proba(X_test)
print(Y_pred_prob)

[[0.99673949 0.00326051]
 [0.99673949 0.00326051]
 [0.99673949 0.00326051]
 ...
 [0.99673949 0.00326051]
 [0.99673949 0.00326051]
 [0.99673949 0.00326051]]


In [68]:
for a in np.arange(0.4,0.70,0.01):
    predict_mine = np.where(Y_pred_prob[:,1] > a, 1, 0)
    cfm=confusion_matrix(Y_test, predict_mine)
    total_err=cfm[0,1]+cfm[1,0]
    print("Errors at threshold ", a, ":",total_err, " , type 2 error :",
          cfm[1,0]," , type 1 error:", cfm[0,1]) 

Errors at threshold  0.4 : 174  , type 2 error : 63  , type 1 error: 111
Errors at threshold  0.41000000000000003 : 174  , type 2 error : 63  , type 1 error: 111
Errors at threshold  0.42000000000000004 : 174  , type 2 error : 63  , type 1 error: 111
Errors at threshold  0.43000000000000005 : 174  , type 2 error : 63  , type 1 error: 111
Errors at threshold  0.44000000000000006 : 174  , type 2 error : 63  , type 1 error: 111
Errors at threshold  0.45000000000000007 : 174  , type 2 error : 63  , type 1 error: 111
Errors at threshold  0.4600000000000001 : 174  , type 2 error : 63  , type 1 error: 111
Errors at threshold  0.4700000000000001 : 174  , type 2 error : 63  , type 1 error: 111
Errors at threshold  0.4800000000000001 : 174  , type 2 error : 63  , type 1 error: 111
Errors at threshold  0.4900000000000001 : 174  , type 2 error : 63  , type 1 error: 111
Errors at threshold  0.5000000000000001 : 174  , type 2 error : 63  , type 1 error: 111
Errors at threshold  0.5100000000000001 : 

In [69]:
from sklearn import metrics

fpr, tpr, z = metrics.roc_curve(Y_test, Y_pred_prob[:,1])
auc = metrics.auc(fpr,tpr)
print(auc)

0.8969834823797519


In [ ]:
#predicting using the Bagging_Classifier
from sklearn.ensemble import RandomForestClassifier
 
model=RandomForestClassifier(100,random_state=10)
#fit the model on the data and predict the values
model=model.fit(X_train,Y_train)
 
Y_pred=model.predict(X_test)

In [71]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)
print(classification_report(Y_test,Y_pred))
acc=accuracy_score(Y_test,Y_pred)
print('Accuracy of the model:',acc)

[[ 94566 162114]
 [     1    310]]
              precision    recall  f1-score   support

         0.0       1.00      0.37      0.54    256680
         1.0       0.00      1.00      0.00       311

    accuracy                           0.37    256991
   macro avg       0.50      0.68      0.27    256991
weighted avg       1.00      0.37      0.54    256991

Accuracy of the model: 0.3691802436661206
